name: rectangoo
favicon: null
layout_spectrum: 0.34808
typography_spectrum: 0.9254489338491112
title: Goltangoo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c070b'
    - '#ffffff'
    - '#a8afa8'
    - '#552a24'
    - '#46690b'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
