name: rectangoo
favicon: null
layout_spectrum: 0.7495605391450226
typography_spectrum: 0.9254489338491112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8756471946835518
  lightness: 0.8436378887854517
  saturation: 0.8573019437026232
  rhythmicContrast: 0.6745571112260222
purpose: []
